app:
  title: "Pro Sales Analytics"
  subtitle: "Unlock Insights for Smarter Decisions"
  logo_url: "https://img.freepik.com/free-vector/indian-chai-tea-glass-promo-poster_1017-60340.jpg?semt=ais_wordcount_boost&w=740&q=80"
  author: "Senior Data Scientist"
  year: 2026
  password: "admin123"  # Change this in production

theme:
  primary_color: "#FF4B4B"
  background_color: "#FFFFFF"
  secondary_background_color: "#F0F2F6"
  text_color: "#262730"
  font: "sans serif"

dark_theme:
  primary_color: "#FF4B4B"
  background_color: "#0E1117"
  secondary_background_color: "#161B22"
  text_color: "#FAFAFA"
  font: "sans serif"
